# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_fn <- function() {
    invisible(.Call(`_htslibr_test_fn`))
}

check_format <- function(fname) {
    .Call(`_htslibr_check_format`, fname)
}

extract_sequence <- function(bam, index, reg) {
    .Call(`_htslibr_extract_sequence`, bam, index, reg)
}

count_kmer <- function(bam, index, reg, kmer) {
    .Call(`_htslibr_count_kmer`, bam, index, reg, kmer)
}

gc_content <- function(bam, index, reg) {
    .Call(`_htslibr_gc_content`, bam, index, reg)
}

depth <- function(bam, index, reg, flank_bp) {
    .Call(`_htslibr_depth`, bam, index, reg, flank_bp)
}

